<?php
/**
 * Additional information template.
 *
 * @author Alex Ghiban <drew7721@gmail.com>
 *
 * @var \JustinKase\LayoutHints\Block\Info $block
 */
?>
<?php if($block->isDeveloperMode()): ?>
    <div class="justinkase-hint-footer">
        <h4>Used Layout Update Handles</h4>
        <pre><?php  var_export($block->getLayout()->getUpdate()->getHandles());?></pre>
        <h4>Suggested Available Containers</h4>
        <pre><?php  var_export($block->getLayout()->getUpdate()->getContainers());?></pre>
    </div>
<?php endif; ?>
